### ISSUE TITLE
Fix crates.io release notes

### ISSUE THREAD

**Issue by Sambigeara** [cerbos/cerbos-sdk-rust#8]
At present, [releases on crates.io](https://crates.io/crates/cerbos/versions) incorrectly list the same `testcontainers` feature for each version.

<img width="551" alt="image" src="https://github.com/cerbos/cerbos-sdk-rust/assets/11599982/2e8229c0-5389-4838-be1d-e72c100b9550">

**Comment by charithe** [comment]
I think the `feature` here refers to [optional features supported by the crate](https://doc.rust-lang.org/cargo/reference/features.html). We have one defined here for enabling `testcontainers`: https://github.com/cerbos/cerbos-sdk-rust/blob/9dc09fbe72362291d08b6ec7bbfa6df49f3c61cd/Cargo.toml#L12-L13

**Comment by Sambigeara** [comment]
Oh I totally misinterpreted that. Thanks
